### ISSUE TITLE
Enable hostingcommunication table

### ISSUE THREAD

**Issue by jonathan-s** [thegreenwebfoundation/greenwebfoundation-admin#29]
We couldn't run the migration for hostingcommunication, it failed with a foreign key constraint that couldn't be created due to myisam / innodb incompability. See: https://github.com/thegreenwebfoundation/thegreenwebfoundation/issues/39

This issue makes sure that we:
* [x] That we revert the following PR: https://github.com/thegreenwebfoundation/greenwebfoundation-admin/pull/28
* [x] Run the accounts 0006 migration, so that it succeeds.

**Comment by jonathan-s** [comment]
@mrchrisadams To avoid any future confusion, perhaps it would be good to delete the 0006 migration and then revert that and #28 when this works properly.

**Comment by mrchrisadams** [comment]
Hi @jonathan-s, updated the storage engine for the table that has resolved this.

**Comment by jonathan-s** [comment]
@mrchrisadams Just to double check. You updated the hostingcommunication table to myisam presumably?

**Comment by mrchrisadams** [comment]
I updated the hosting providers table.

We hit the size limit with MyISAM for the massive greencheck table, so we had to created a new table with InnoDB.

```
ALTER TABLE hostingproviders ENGINE = InnoDB;
```

**Comment by jonathan-s** [comment]
So new greencheck table is in InnoDB as well now? Because if I remember correctly that was the main blocker to convert all tables to InnoDB.

**Comment by mrchrisadams** [comment]
Indeed. Praise be :)
