### ISSUE TITLE
Admin site at least needs an name

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/greenwebfoundation-admin#47]
Right now, the green-urls url shows the site as django administration, with no guidance on what's in the datasets made available.

We'd need

- the admin to be named - _Green Web Foundation Administration_ would be fine
- some linking to documentation for how to use the datasets and what the columns in the datasets correspond to (this [documentation here would be sufficient til we have something more complete on the main website][1], for example)

[1]: https://github.com/thegreenwebfoundation/greenwebfoundation-admin/blob/master/docs/working-with-greenweb-datasets.md

**Comment by mrchrisadams** [comment]
Closed by #49.

**Comment by jonathan-s** [comment]
Not closed by #49. #48 closes #49. So this still remains open.

**Comment by mrchrisadams** [comment]
Whoops! Yeah, I totally added this to the wrong tab…
