### ISSUE TITLE
New users see permissions and important dates when they shouldn't

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/greenwebfoundation-admin#55]
If you create a new user, when you sign up, you see more permissions that you should.

Specifically, you see:

- user and group permissions
- staff / superuser
- important dates

These should be visible to super users, but not end users.

### Where this seems to be occuring

I _think_ this is down to the admin page being overridden here, where there are explicit listings of admin widgets.

https://github.com/thegreenwebfoundation/greenwebfoundation-admin/blob/master/apps/accounts/admin.py#L58-L71

I say this because there don't seem to be permissions associated with the hosting group that would list these widgets otherwise.

**Comment by jonathan-s** [comment]
I believe that you would need to change this -> https://github.com/django/django/blob/master/django/contrib/auth/admin.py#L65

**Comment by mrchrisadams** [comment]
Closed with the PR in #58
